server:
  port: 9090

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: http://localhost:8081
          predicates:
          - Path=/com.amazingcode.in/api/employees/**

        - id: address-service
          uri: http://localhost:8082
          predicates:
          - Path=/com.amazingcode.in/api/addresses/**
#
#server:
#  port: 9090
#spring:
#  application:
#    name: api-gateway-service
#  cloud:
#    gateway:
#      routes:
#        - id: employee-service
#          uri: http://localhost:8081
#          predicates:
#            - Path=/com.amazingcode.in/api/employees/**
#        - id: address-service
#          uri: http://localhost:8082
#          predicates:
#            - Path=/com.amazingcode.in/api/addresses/**
